### GET all locations

GET http://localhost:3001/api/locations HTTP/1.1

### GET a single location by attribute

GET http://localhost:3001/api/locations/search?landscape=city&infrastructure=power HTTP/1.1


### POST a location
POST http://localhost:3001/api/locations HTTP/1.1
Content-Type: application/json

{
    "address": "Mittenwalder Str. 97, 82431 Kochel am See",
    "landscape": "lake",
    "infrastructure": "waste",
    "latitude": 47.64159,
    "longitude": 11.35814,
    "imageUrl": "src/assets/LocationImages/KochelLake.jpg",
    "id": 12
}

### Delete a location
DELETE http://localhost:3001/api/locations/48.518159 HTTP/1.1
