### GET all locations

GET http://localhost:3001/api/locations HTTP/1.1

### GET a single location by attribute

GET http://localhost:3001/api/locations/search?landscape=city&infrastructure=power HTTP/1.1


### POST a location
POST http://localhost:3001/api/locations HTTP/1.1
Content-Type: application/json

{
    "address": "Kurhausstraße 18, 79674 Todtnau",
    "landscape": "mountains",
    "infrastructure": "timelimit",
    "latitude": 47.84389,
    "longitude": 7.93614,
    "imageUrl": "https://res.cloudinary.com/dbbp26ulk/image/upload/v1639913417/LocationImages/TodtnauVan_zkn6hm.jpg",
    "id": 2
}

### Delete a location
DELETE http://localhost:3001/api/locations/48.518159 HTTP/1.1
